BlackJack/Controllers/OnLineController.cs
using Classes;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BlackJack.Controllers
{
    public class OnLineController : MasterController
    {
        public IActionResult Index()
        {
            Gioco gioco = Gioco.GiocoBuilder.Init()
                .AggiungiNome("On line")
                .AggiungiMazzi(6)
                .build();

            gioco.Giocatori.Add(GiocatoreBuilder.Init()
                .AggiungiGioco(gioco)
                .AggiungiStrategia(new BasicStrategy())
                .build());

            Partite.Add(gioco);

            return View();
        }

        public JsonResult PescaCarta(int valore, int soggetto)
        {
            Gioco gioco = Partite.Where(q => q.Nome == "On line").FirstOrDefault();
            Giocatore giocatore = gioco.Giocatori.First();
            gioco.Mazzo.Carte[0] = new Carta((Carta.NumeroCarta)valore, Carta.SemeCarta.Cuori);
            if (soggetto == 0)
                gioco.Mazziere.Chiama();
            else if (soggetto == 1)
                giocatore.Chiama();
            
            return Json(new { numcarte = gioco.Mazzo.Carte.Count, truecount = giocatore.Strategia.TrueCount });
        }

        public JsonResult NuovaMano()
        {
            Gioco gioco = Partite.Where(q => q.Nome == "On line").FirstOrDefault();

            return Json(JsonGioco(gioco));
        }

        public JsonResult GetOperazione()
        {
            Gioco gioco = Partite.Where(q => q.Nome == "On line").FirstOrDefault();
            Giocatore giocatore = gioco.Giocatori.First();

            Giocatore.Giocata? puntata = GiocatoreSemplice.Giocata.Chiama;
            if (giocatore.Carte.Count > 0 && gioco.Mazziere.Carte.Count > 0)
                puntata = giocatore.Strategia.Strategy(giocatore, gioco.Mazziere, gioco.Mazzo.Carte.Count);

            return Json(new { 
                operazione = gioco.Mazziere.Carte.Count + giocatore.Carte.Count >= 3 ? Enum.GetName(typeof(Giocatore.Giocata), puntata) : "Seleziona carta",
                puntimiei = giocatore.Punteggio,
                puntimazziere = gioco.Mazziere.Punteggio,
                numcarte = gioco.Mazzo.Carte.Count
            });
        }

        //public JsonResult GetOperazione(List<int> cartaMazziere, List<int> carteMie, int conteggio)
        //{
        //    Giocatore giocatore = GiocatoreBuilder.Init().AggiungiGioco(null).AggiungiStrategia(new BasicStrategy()).build();
        //    foreach(int numcarta in carteMie)
        //    {
        //        giocatore.Carte.Add(new Carta((Carta.NumeroCarta)numcarta, Carta.SemeCarta.Cuori));
        //    }
        //    Mazziere mazziere = new Mazziere(null);
        //    mazziere.Carte.Add(new Carta((Carta.NumeroCarta)cartaMazziere.FirstOrDefault(), Carta.SemeCarta.Picche));

        //    Giocatore.Puntata operazione = giocatore.Strategia.Strategy(giocatore, mazziere, conteggio);

        //    return Json(operazione.ToString());
        //}

        public JsonResult GetPuntata(List<int> cartaMazziere, List<int> carteMie, int conteggio)
        {
            Giocatore giocatore = GiocatoreBuilder.Init().AggiungiGioco(null).AggiungiStrategia(new BasicStrategy()).build();
            foreach (int numcarta in carteMie)
            {
                giocatore.Carte.Add(new Carta((Carta.NumeroCarta)numcarta, Carta.SemeCarta.Cuori));
            }
            Mazziere mazziere = new Mazziere(null);
            mazziere.Carte.Add(new Carta((Carta.NumeroCarta)cartaMazziere.FirstOrDefault(), Carta.SemeCarta.Picche));

            decimal puntata = giocatore.Strategia.Puntata(giocatore, 1, 1, conteggio);

            return Json(puntata);
        }


    }
}

BlackJack/Controllers/TestController.cs
using BlackJack.Models;
using Classes;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace BlackJack.Controllers
{
    public class TestController : MasterController
    {

        public IActionResult TestCount()
        {

            return View();
        }

        public IActionResult TestStrategia()
        {
            Gioco gioco = Gioco.GiocoBuilder.Init()
                .AggiungiNome("Partita Test")
                .AggiungiNumeroGiocatori(0)
                .AggiungiMazzi(6)
                .build();

            //gioco.Mazzo.Carte[2].Numero = gioco.Mazzo.Carte[0].Numero; //riga di test per lo split
            //gioco.Mazzo.Carte[2].PathImage = gioco.Mazzo.Carte[0].PathImage;
            //gioco.Mazzo.Carte[4].Numero = gioco.Mazzo.Carte[0].Numero;
            //gioco.Mazzo.Carte[4].PathImage = gioco.Mazzo.Carte[0].PathImage;
            //gioco.Mazzo.Carte[5].Numero = gioco.Mazzo.Carte[0].Numero;
            //gioco.Mazzo.Carte[5].PathImage = gioco.Mazzo.Carte[0].PathImage;

            gioco.Id = "test";
            gioco.Inizializza();
            Partite.Add(gioco);

            Giocatore giocatore = GiocatoreBuilder.Init().AggiungiGioco(gioco).AggiungiStrategia(new BasicStrategy()).build();
            giocatore.Id = "test";
            HttpContext.Session.SetString("IdGiocatore", giocatore.Id);
            gioco.Giocatori.Add(giocatore);

            return RedirectToAction("Partita", "Home", new { id = gioco.Id });

            //return View();
        }
        public IActionResult TestStrategy()
        {

            return View();
        }
        public IActionResult Index()
        {
            Gioco gioco = Gioco.GiocoBuilder.Init()
                .AggiungiNumeroGiocatori(0)
                .AggiungiMazzi(6)
                .AggiungiMischiata()
                .AggiungiPuntataMinima(5)
                .AggiungiPercentualeMischiata(50)
                .build();

            gioco.Mazziere.SoldiTotali = 100;

            gioco.Giocatori.Add(GiocatoreBuilder.Init()
                .AggiungiGioco(gioco)
                .AggiungiStrategia(new BasicStrategy()).build());

            gioco.Giocatori.Add(GiocatoreBuilder.Init()
                .AggiungiGioco(gioco)
                .AggiungiStrategia(new StrategiaPunteggio()).build());

            SetSessionGioco(gioco);

            return View();
        }

        [HttpPost]
        public JsonResult GetGioco(int? numGiri)
        {
            Gioco gioco = GetSessionGioco();
            int giri = numGiri ?? 1;
            for (int i = 0; i < giri; i++)
            {
                gioco.Giocata();
            }

            SetSessionGioco(gioco);

            return Json(new { gioco = JsonConvert.SerializeObject(gioco) });
        }


        void SetSessionGioco(Gioco gioco)
        {
            JsonSerializerSettings settings = new JsonSerializerSettings();
            settings.DefaultValueHandling = DefaultValueHandling.Ignore;
            var giocatorijson = JsonConvert.SerializeObject(gioco.Giocatori);
            HttpContext.Session.SetString("Giocatori", giocatorijson);
            var giocatori = gioco.Giocatori;

            gioco.Giocatori = null;
            var gi = JsonConvert.SerializeObject(gioco, settings);
            HttpContext.Session.SetString("Gioco", gi);
            gioco.Giocatori = giocatori;
        }

        Gioco GetSessionGioco()
        {
            string json = HttpContext.Session.GetString("Giocatori");
            List<Giocatore> giocatori = JsonConvert.DeserializeObject<List<Giocatore>>(json);

            json = HttpContext.Session.GetString("Gioco");
            Gioco gioco = JsonConvert.DeserializeObject<Gioco>(json);
            gioco.Giocatori = giocatori;
            gioco.Mazziere.Gioco = gioco;
            gioco.Giocatori.ForEach(q => q.Gioco = gioco);

            return gioco;
        }


        [HttpPost]
        public JsonResult GetCarteTest()
        {
            Gioco gioco = Gioco.GiocoBuilder.Init().AggiungiNumeroGiocatori(0).build();
            for (int i = 0; i < 20; i++)
            {
                gioco.Mazziere.Chiama();
            }
            return Json(new { gioco = JsonConvert.SerializeObject(gioco) });
        }

        [HttpPost]
        public JsonResult GetCarteTestStrategy()
        {
            Gioco gioco = Gioco.GiocoBuilder.Init().AggiungiNumeroGiocatori(1).build();
            gioco.Mazziere.Chiama();
            gioco.Giocatori[0].Chiama();
            gioco.Giocatori[0].Chiama();

            return Json(new { gioco = JsonConvert.SerializeObject(gioco) });
        }


    }
}

BlackJack/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BlackJack</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">    
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.6.3.min.js"
            integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU="
            crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BlackJack</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="Index">Test gioco</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="TestCount">Test Count</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="TestStrategy">Test Strategy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Test" asp-action="TestStrategia">Test Strategia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="OnLine" asp-action="Index">Gioco on line</a>
                        </li>
@*                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link disabled">Disabled</a>
                        </li>*@
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div id="dialogMessage" title="">
    </div>
    <div id="dialogConfirm" title="">
    </div>

    <div class="modal fade" id="DialogMessage" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="DialogMessageTitle"></h5>
                </div>
                <div id="DialogMessageBody" class="modal-body"></div>
                <div class="modal-footer btnMessage">
                    <button type="button" class="btn btn-success" data-dismiss="modal" onclick="if (_messageCallback != undefined){_messageCallback()}; CloseDialogMessage();">Ok</button>
                </div>
                <div class="modal-footer btnConfirm">
                    <button type="button" class="btn btn-success" data-dismiss="modal" onclick="if (_confirmCallback != undefined){_confirmCallback()}; CloseDialogMessage();">Si</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="CloseDialogMessage();">No</button>
                </div>
            </div>
        </div>
    </div>

    <div class="container container-100">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BlackJack - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>